/number_publisher1:
  ros__parameters:
    number: 10
    timer_period: 0.5

/number_publisher2:
  ros__parameters:
    number: 7
    timer_period: 1.2

/led_panel_client:
  ros__parameters:
    led_states: [1, 0, 1, 1]

/robot_news:
  ros__parameters:
    robot_name: "APNA"
